### ISSUE TITLE
mvn central for 0.1.10

### ISSUE THREAD

**Issue by gjesse** [pszymczyk/embedded-consul#17]
Just fyi I tried to update to the latest version, and the latest available in mvn central is 0.1.9

**Comment by pszymczyk** [comment]
Hi I've just forgot to click release button on Sonatype :). 0.1.10 is on central now: http://search.maven.org/#artifactdetails%7Ccom.pszymczyk.consul%7Cembedded-consul%7C0.1.10%7Cjar.
