### ISSUE TITLE
Bump consul version to 0.7.1

### ISSUE THREAD

**Issue by Sandmania** [pszymczyk/embedded-consul#25]
Consul 0.7.1 has been released. Making embedded-consul use that, should fix #22

**Comment by pszymczyk** [comment]
```
:check
:build

BUILD SUCCESSFUL

Total time: 1 mins 13.831 secs

```
On my mac os sierra :)
Great!, I will bump it and release now. Much thanks @Sandmania.

**Comment by pszymczyk** [comment]
embedded-consul-0.2.2 should be available in few minutes in maven central.

**Comment by Sandmania** [comment]
Awesome. Waiting eagerly for it to appear in central.
