### ISSUE TITLE
Consul start speed

### ISSUE THREAD

**Issue by dvayanu** [pszymczyk/embedded-consul#32]
Hello,

first of all many thanks for this great project. 
We are developing/maintaining DistributeMe project: http://www.distributeme.org. DistributeMe is a code generation framework for microservices communication over rmi. Usually DistributeMe uses its own registry to exchange information about services. However we recently added a new module that allows to use consul as service registry.
To unit-test our code we are using your project in a unit-test:
https://github.com/parship/distributeme/blob/master/distributeme-consul-registry-connector/src/test/java/org/distributeme/consulintegration/ConsulRegistryConnectorIntegrationTest.java

First of all: it works great. However, the execution duration of own two-test testrun is 22 seconds. Now the question: is there any option/way to speed up start of the consul registry in the unit-test mode, to reduce the execution time to an acceptable amount for a unit-test?

Thank you for your time!

**Comment by pszymczyk** [comment]
Hi

It's really nice to hear that you enjoy embedded-consul :)

Hmm 22 seconds it's quite long :/ I've checked it on my local machine (mackbook pro i7 16gb) and it tooks about 7s for whole test (setup and cleanup included). It's a little bit better than 22s but still its's quite long :/ here are some logs:

```
14:42:55.850 [main] INFO com.pszymczyk.consul.ConsulStarter - Starting new Consul process.
14:42:55.878 [main] INFO com.pszymczyk.consul.ConsulStarter - Creating ports configuration file: /var/folders/ml/vzt9p7fs5wvfz7wtjclg1q00kggz96/T/embedded-consul-config-dir1769571288582229943/basic_config.json
14:42:55.889 [main] INFO com.pszymczyk.consul.ConsulStarter - Creating custom configuration file: /var/folders/ml/vzt9p7fs5wvfz7wtjclg1q00kggz96/T/embedded-consul-config-dir1769571288582229943/extra_config.json
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
           Version: 'v0.7.1'
         Node name: 'c50906'
        Datacenter: 'test-dc'
            Server: true (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 54361, HTTPS: -1, DNS: 12121, RPC: 54362)
      Cluster Addr: 127.0.0.1 (LAN: 54363, WAN: 54364)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

14:43:02.009 [main] INFO com.pszymczyk.consul.ConsulProcess - Stopping Consul process running on port 54361
==> Caught signal: terminated
14:43:02.013 [main] INFO com.pszymczyk.consul.ConsulProcess - Stopped Consul process running on port 54361
```

As yo can read in readme embedded-consul downloads and unpacks consul binary into some temp directory, maybe in your setup binary is downloaded again and again? 

Try to download binary manually and pass directory in embedded-consul builder:

```
ConsulStarterBuilder.consulStarter().withConsulBinaryDownloadDirectory(binary location here)
``` 

I'm not sure that it would helps but it's easy to check it.

I will also check what actually takes the largest number of time by debugging code.

**Comment by pszymczyk** [comment]
@dvayanu great news! I've checked that Consul is waiting for leader election for about 7seconds :/ fortunately there is some interesting property in Consul:
https://www.consul.io/docs/agent/options.html#raft_multiplier
which set to 1 speed-up leader election to ~2seconds 👍

**Comment by dvayanu** [comment]
Thanks, sounds great, I will try to test it as soon as possible (which will be most probably late friday or weekend)

**Comment by dvayanu** [comment]
I've built 0.2.4-SNAPSHOT locally and tested with it, the test runs much faster. How can we get to a 0.2.4 released version? :-)

**Comment by pszymczyk** [comment]
I have to do some "magic" 😄

**Comment by pszymczyk** [comment]
@dvayanu embedded-consul 0.3.0 should be available in few minutes, sry for delay but i had problem with jdk7 :(

**Comment by pszymczyk** [comment]
http://central.maven.org/maven2/com/pszymczyk/consul/embedded-consul/0.3.0/

**Comment by dvayanu** [comment]
Thanks, yes I tested it already and it worked within 6 seconds. Thank you.
