### ISSUE TITLE
Missing Changelog or release notes

### ISSUE THREAD

**Issue by janisz** [pszymczyk/embedded-consul#37]
It's hard to find what has changed between two releases. I assume we should use latest version but I would love to see what has changed.

http://keepachangelog.com/en/0.3.0/

**Comment by szpak** [comment]
Available for 2.2.0+ as a separate file:
https://github.com/pszymczyk/embedded-consul/blob/master/CHANGELOG.md
or GitHub release notes:
https://github.com/pszymczyk/embedded-consul/releases/tag/release%2F2.2.0
