### ISSUE TITLE
Custom config not applied

### ISSUE THREAD

**Issue by shortstories** [pszymczyk/embedded-consul#38]
My project is using Spring boot, and I am using Embedded consul in test and local environment. When I modified my code to test other consul options, I found that it doesn't applied.

So, I opened last `extra_config.json` file and I could see something like this:

``` json
{"ui":true,"enable_debug":true,"node_name":"test_local_node"}{"server":true,"ui":true,"enable_debug":true,"node_name":"test_local_node"}{"server":true,"ui":true,"enable_debug":true,"node_name":"test_local_node"}{"server":true,"ui":true,"dev":true,"enable_debug":true,"node_name":"test_local_node"}{"server":true,"ui":true,"dev":true,"enable_debug":true,"node_name":"test_local_node"}
```

In the default options, each process starting creates each temp directories, so it doesn't cause problem. But in my case, a problem occurred because I set a specific config directory.

So It seems that we need to change `ResourceGroovyMethods.leftShift()` to `ResourceGroovyMethods.setText()`.

**Comment by pszymczyk** [comment]
released: http://central.maven.org/maven2/com/pszymczyk/consul/embedded-consul/0.3.1/

@shortstories Many thanks for your contribution!
