### ISSUE TITLE
Not downloading consul binary when configured version changes

### ISSUE THREAD

**Issue by pbetkier** [pszymczyk/embedded-consul#40]
On the first run embedded consul downloads a consul binary in a given version into a temporary directory. On subsequent runs it doesn't attempt to download the binary again if it's already present. This means that embedded consul always uses the consul version that was configured for its first run, regardless of later changes to the consul version configured.

Solution: embedded consul should cache consul binaries in its temporary directory by version.

**Comment by pszymczyk** [comment]
Hi 

I think it's resolved already https://github.com/pszymczyk/embedded-consul/pull/34.

**Comment by pbetkier** [comment]
Exactly, I've just found out :) thx.
