### ISSUE TITLE
Grant possibility to bind embedded consul to another network interface

### ISSUE THREAD

**Issue by SchulteMarkus** [pszymczyk/embedded-consul#41]
Hi there,

it seems to me, as if embedded consul would be fixed to 127.0.0.1 as listening ip addr (see [ConsulStarter.groovy](https://github.com/pszymczyk/embedded-consul/blob/master/src/main/groovy/com/pszymczyk/consul/ConsulStarter.groovy#L102)).

Please provide a possibility, to bind embedded-consul to another IP (or 0.0.0.0).

**Comment by pszymczyk** [comment]
Hi Marcus

It's very easy to implement it, I wish you did not try to implement yourself ;)
Here is PR: https://github.com/pszymczyk/embedded-consul/pull/42

**Comment by SchulteMarkus** [comment]
Hi @pszymczyk ,

thank you!
I wish you had written embedded-consul in Java ;-)
