### ISSUE TITLE
Consul 1.0.0 compatibility

### ISSUE THREAD

**Issue by lazystone** [pszymczyk/embedded-consul#51]
Seems like 0.3.5 is incompatible with Consul 1.0.0
Since 1.0.0 considered to be major and first release it would be really nice to align with Consul 1.0.0

At the moment I get
```
10:04:23.715 [main] INFO com.pszymczyk.consul.ConsulStarter - Starting new Consul process.
10:04:23.730 [main] INFO com.pszymczyk.consul.ConsulStarter - Creating ports configuration file: /var/folders/2s/wvgn1t095wjbsc8sbby6m2zh0000gn/T/embedded-consul-config-dir702655073261408839/basic_config.json
==> Error parsing /var/folders/2s/wvgn1t095wjbsc8sbby6m2zh0000gn/T/embedded-consul-config-dir702655073261408839/basic_config.json: 1 error(s) occurred:

* invalid config key ports.rpc
```

As mentioned [here](https://www.consul.io/docs/upgrade-specific.html#consul-1-0):

Removed Option | Equivalent
-- | --
ports.rpc | None, the RPC server for CLI commands is no longer supported.

**Comment by lazystone** [comment]
Seems like consul-api must be brought up to date as well: Ecwid/consul-api#130

**Comment by pszymczyk** [comment]
Sure but look that it's only test dependency, real communication is done by groovy http library

**Comment by lazystone** [comment]
Actually I looked a little bit, seems like its easy to fix, but found some differences in behaviour:
* ConsulStarterTest."should remove all services when reset Consul process": consulClient.getAgentServices().value.size() after reset returns 0 now.
* ConsulStarterTest."should deregister all checks when reset Consul process" fails unless I change newCheck.ttl to newCheck.interval
* ConsulStarterNodeNameIdTest fails because NodeId was taken out from the Config. Now it's a part of DebugConfig

**Comment by pszymczyk** [comment]
I need some time too look at it, but do not hesitate to do some pull request if some tests are failing I'll try to help with that.

**Comment by pszymczyk** [comment]
1.0.0 is in mvn central:
https://mvnrepository.com/artifact/com.pszymczyk.consul/embedded-consul/1.0.0
great job @lazystone!! thx.
