### ISSUE TITLE
Ability to use proxy to download consul binary

### ISSUE THREAD

**Issue by seppaleinen** [pszymczyk/embedded-consul#64]
First of all thanks for a brilliant lib!

Working behind a proxy makes downloading the consul-binary impossible.
It would be nice to be able to pass some information, so that a proxy is configured.

Either by environment variables as with the CONSUL_BINARY_CDN, or by adding a constructor with the extra fields.

Thanks again!

**Comment by ruslansennov** [comment]
What about the system properties `http.proxyHost` and `http.proxyPort`?

**Comment by pszymczyk** [comment]
@ruslansennov if you are 100% sure that system proxy do the job we can add some manual to readme.md

**Comment by ruslansennov** [comment]
I'm not sure, but I'll check it out
