### ISSUE TITLE
Consul download - check for prior existence fails on Windows

### ISSUE THREAD

**Issue by Jwvdo01** [pszymczyk/embedded-consul#66]
For Windows (not *nix) - the check for existence of Consul in the specified (or unspecified) download directory does not work. It is re-downloaded every time.

This is because the code looks for the *nix filename 'consul':

```
private boolean isBinaryDownloaded() {
    return new File(downloadDir.toString(), "consul").exists()
}
```

I think this needs to be changed to:

```
private boolean isBinaryDownloaded() {
        String binaryName = 'consul';
        if ('windows' == OsResolver.resolve()) {
            binaryName = 'consul.exe';
        }

        return new File(downloadDir.toString(), binaryName).exists()
}
```

A workround for the moment is to place a file (I copied consul.exe) called 'consul' (no extension) and everything is good to go. Windows only of-course.

**Comment by ruslansennov** [comment]
Hi @Jwvdo01 
Could you make a PR please?
