### ISSUE TITLE
2.1 release tag but doesn't seem to be on maven central yet

### ISSUE THREAD

**Issue by ianoc-stripe** [pszymczyk/embedded-consul#81]
It looks like the latest release hasn't been pushed to maven central. Would it be possible to get it pushed up? 2.0.0 doesn't work isolated very well with the latest consul agents since they will collide on grpc ports. It looks like this is all handled on master/the 2.1.0 release tag so would love if it could be pushed out. 

Thanks!

**Comment by pszymczyk** [comment]
Hi

Yes 2.1.0 is not in mvn central, I have a problem with release caused by bumping Gradle to new version, I will working on that tomorrow.

**Comment by ianoc-stripe** [comment]
Ah, excellent thank you. And thanks for making such a very useful utility!

**Comment by pszymczyk** [comment]
@ianoc-stripe 2.1.2 its finally in mvn central, sry for delay but I had turbulences with release :/ http://central.maven.org/maven2/com/pszymczyk/consul/embedded-consul/2.1.2/
