### ISSUE TITLE
The javadoc and source for version 2.1.2 are empty.

### ISSUE THREAD

**Issue by charleech** [pszymczyk/embedded-consul#85]
The javadoc and source for version 2.1.2 from Maven central are empty.

* https://search.maven.org/remotecontent?filepath=com/pszymczyk/consul/embedded-consul/2.1.2/embedded-consul-2.1.2-javadoc.jar

* https://search.maven.org/remotecontent?filepath=com/pszymczyk/consul/embedded-consul/2.1.2/embedded-consul-2.1.2-sources.jar

**Comment by pszymczyk** [comment]
Hi @charleech 

Thank you for info, yesterday I was reconfiguring java doc and sources generation - https://github.com/pszymczyk/embedded-consul/commit/86d9b4b23195d3b207b8de7bf1837f7478323cb6 - i was connected with new Gradle version, so it is possible that still something needs polishing.

**Comment by pszymczyk** [comment]
@charleech I think it should do the job https://github.com/pszymczyk/embedded-consul/pull/86

**Comment by jordanjennings** [comment]
Can you either re-push the jars or push a new patch release with the fixed javadoc and sources? They are still empty on maven central. Thanks!

**Comment by pszymczyk** [comment]
Check 2.1.4 http://central.maven.org/maven2/com/pszymczyk/consul/embedded-consul/2.1.4/
