### ISSUE TITLE
Tests process get stuck in downloading embedded consul

### ISSUE THREAD

**Issue by LangInteger** [pszymczyk/embedded-consul#91]
It seems that every time I run my tests the embedded consul will be downloaded. Log as follows:

```log
    2019-10-08 15:00:55,751 [Test worker] [] INFO  com.pszymczyk.consul.ConsulStarter.start - Starting new Consul process.
    2019-10-08 15:00:55,777 [Test worker] [] INFO  com.pszymczyk.consul.BinariesManager.downloadAndUnpackBinary - Downloading archives into: /var/folders/32/2n4ht3pj0g97s50v8mhlds340000gn/T/embedded-consul-1.4.2/consul.zip
```

Is there any solution to avoid the unnecessary downloading, such as the zip file is already existed?

**Comment by pszymczyk** [comment]
Hi @LangInteger 

As you can see in docs https://github.com/pszymczyk/embedded-consul#files-structure, library was designed to avoid this unnecessary downloading Consul all the time. If it not works this way right now probably we introduced some bug, can you check your files structure and see why library downloads Consul all the time?

**Comment by LangInteger** [comment]
Ok, I'll try to dig more deep, I'll reopen the issue if any bug found. Thanks for your tips.

**Comment by pszymczyk** [comment]
Cool, if you find something I strongly encourage you to join contributors list :) please do not hesitate to ask if you have some doubts too.
