### ISSUE TITLE
Embedded Nomad?

### ISSUE THREAD

**Issue by cricket007** [pszymczyk/embedded-consul#94]
Hello @pszymczyk , 

Is there any interest in creating an _Embedded Nomad_?

Ref. https://github.com/hashicorp/nomad-java-sdk/issues/39

**Comment by pszymczyk** [comment]
Hi @cricket007 

Personally I don't need this kind of software.

**Comment by cricket007** [comment]
Fair enough. Related question, if you're willing to answer then, what type of infrastructure are you using Consul with?

**Comment by pszymczyk** [comment]
@cricket007 We are not using consul at all right now, we moved to Kubernetes and we use naive Kubernetes tools.

**Comment by cricket007** [comment]
Alright, well, reference if you ever did want to go back to having Consul 

https://www.consul.io/docs/platform/k8s/dns.html#coredns-configuration

**Comment by pszymczyk** [comment]
cool, thanks.
