### ISSUE TITLE
embedded-consul only works on amd64 

### ISSUE THREAD

**Issue by Gibaldiqqq** [pszymczyk/embedded-consul#96]
The platform is amd64 without judgement.  Will it be updated to support other platform.
String url = "${cdn}${version}/consul_${version}_${os}_amd64.zip"

package com.pszymczyk.consul.infrastructure

class HttpBinaryRepository {

    public static final String CONSUL_BINARY_CDN = "CONSUL_BINARY_CDN"
    public static final String CONSUL_DEFAULT_CDN = "https://releases.hashicorp.com/consul/"
    private HttpsProtocolsSetter httpsProtocolsSetter

    HttpBinaryRepository() {
        this.httpsProtocolsSetter = new HttpsProtocolsSetter(new HttpsProtocolsSetter.SystemPropertiesStorage())
    }

    File getConsulBinaryArchive(String version, File file) {
        httpsProtocolsSetter.setRequiredTls(System.getProperty("java.version"), System.getProperty("https.protocols"))
        String os = OsResolver.resolve()
        String cdn = System.getenv(CONSUL_BINARY_CDN) != null ? System.getenv(CONSUL_BINARY_CDN)
                : System.getProperty(CONSUL_BINARY_CDN) != null ? System.getProperty(CONSUL_BINARY_CDN) : CONSUL_DEFAULT_CDN;
        String url = "${cdn}${version}/consul_${version}_${os}_amd64.zip"
        OutputStream outputStream = file.newOutputStream()
        outputStream << new URL(url).openStream()
        outputStream.close()
        file
    }
}

**Comment by rhenwood-arm** [comment]
I'm interested in AArch64 support - has any progress been made that you know of?
